[versions]
androidxCore = "1.12.0"
jna = "5.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
