[book]
authors = ["Ghamza-Jd"]
language = "en"
multilingual = false
src = "src"
title = "Janus Mobile SDK Documenation"
description = "Janus mobile sdk documentation that includes the architecture, sdk installation, usage, and examples."

[output.html]
git-repository-url = "https://github.com/Ghamza-Jd/janus-mobile-sdk"
git-repository-icon = "fa-github"

[output.html.playground]
runnable = false

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
